Updated the template and readme
gluster/community pull request #42
Opened 2020-10-30 09:48 UTC by nik-redhat

Updated the meeting minutes template and the readme so as to reflect the latest changes like the change of platform to google meet, removing NA meeting schedule, updated the calendar and also updated few meeting topics as they are no more useful or are generally empty.

Signed-off-by: nik-redhat <nladha@redhat.com>

2020-10-30 09:53 UTC, nik-redhat commented
@Sheetalpamecha can you please review this.

2020-10-30 10:14 UTC, Sheetalpamecha requested changes

2020-10-30 10:14 UTC, Sheetalpamecha commented on README.md
>  APAC/EMEA Schedule -
Not required to mention specific regions. Schedule sounds good

2020-10-30 10:14 UTC, Sheetalpamecha commented on template.md
>    - Tuesday {Date}, 02:30PM IST
Tuesday/Thursday

2020-10-30 10:14 UTC, Sheetalpamecha commented on template.md
>  * APAC/EMEA friendly hours
Not required to mention specific regions.

2020-10-30 10:16 UTC, Sheetalpamecha commented
In template.md Under metrics section we can remove "New Bugs in last 14 days" and "Total Bugs" rows

2020-10-30 10:17 UTC, nik-redhat commented on template.md
>    - Tuesday {Date}, 02:30PM IST
Do we have meetings on Thursday's?

2020-10-30 10:17 UTC, nik-redhat commented
Will make the changes.

2020-10-30 11:02 UTC, Sheetalpamecha commented on template.md
>    - Tuesday {Date}, 02:30PM IST
yes Tuesdays right. I got confused

2020-11-02 02:19 UTC, Sheetalpamecha approved these changes

2020-11-02 02:19 UTC, merged